#!bin/bash
# this is the Makefile for Project2

CC = gcc
CFLAGS = -I. -g
TARGETS = runsim testsim
RUNSIM = runsim license.h
TESTSIM = testsim
SRC =
SRC2 =

all: $(TARGETS)
r: ${(RUNSIM)
t: $(TESTSIM)


